pion/ion-avp

go.mod
go.sum
pkg/avp.go
pkg/pipeline.go
pkg/samples/builder.go
pkg/webrtctransport.go

cleanup when remote removes a track

handle remove track

---

go.mod
pkg/registry_test.go

Added test for registry
Created mock element to implement mock interface
Fixes #...

Test Registry

---

cmd/server/grpc/main.go
examples/save-to-webm/server/main.go
pkg/avp.go
pkg/registry.go
pkg/registry_test.go
pkg/webrtctransport.go

pass through config bytes to element constructors

feat(element): pass config

---

go.mod
go.sum
pkg/builder.go
pkg/builder_test.go

added test for builder
changed elements from map[string]Element to avoid race condition
in builder.forward() changed from read only locks to read/write locks
Fixes #...

Test Builder

---

go.mod
pkg/registry_test.go
pkg/webrtctransport_test.go

Added tests for transport

---

go.sum
pkg/elements/webm_test.go

chore(webmsaver): add test

---

pkg/elements/webm_test.go

chore(webm): opus test

---

pkg/elements/webm.go
pkg/webrtctransport.go
pkg/webrtctransport_test.go

feat(process): single process per pid

---

pkg/elements/webm.go

feat(webmsaver): use seek head

---

go.mod
go.sum
pkg/elements/decoder.go
pkg/elements/elements.go
pkg/elements/webm.go

computer vision on streams now super easy :D

feat(decoder): decode vp8 stream keyframes to YCbCr image frames

---

pkg/elements/converter.go
pkg/elements/decoder.go
pkg/elements/elements.go

feat(converter): convert YCbCR -> JPEG

---

examples/save-to-webm/server/main.go
pkg/builder.go
pkg/element.go
pkg/elements/converter.go
pkg/elements/decoder.go
pkg/elements/filewriter.go
pkg/elements/filter.go
pkg/elements/webm.go
pkg/elements/webm_test.go
pkg/registry_test.go

feat(filter): filter element + interface cleanup

---

pkg/elements/decoder.go

fix(decoder): fps float

---

go.mod
go.sum
pkg/builder.go
pkg/elements/elements.go
pkg/elements/multiplexer.go
pkg/sample.go

feat(elements): multiplexer

---

pkg/elements/decoder.go

fix(elements): decoder async producer

---

.github/workflows/docker-grpc.yaml
.gitignore
Dockerfile
Makefile
cmd/signal/grpc/Dockerfile
cmd/signal/grpc/main.go
cmd/signal/grpc/proto/avp.pb.go
cmd/signal/grpc/proto/avp.proto
cmd/signal/grpc/proto/avp_grpc.pb.go
cmd/signal/grpc/server/avp.go
cmd/signal/grpc/server/server.go
cmd/signal/grpc/server/sfu.go
config.toml
examples/save-to-webm/README.md
examples/save-to-webm/client/main.go
examples/save-to-webm/server/config.toml
examples/save-to-webm/server/main.go
pkg/avp.go
pkg/conf.go
pkg/registry.go
pkg/webrtctransport.go
pkg/webrtctransport_test.go
scripts/build_protos.sh

Modularize server, pkg not depend grpc

Modularize server, pkg not depend grpc

---

cmd/signal/grpc/server/avp.go
cmd/signal/grpc/server/server.go
cmd/signal/grpc/server/sfu.go
examples/save-to-webm/client/main.go
pkg/webrtctransport.go
pkg/webrtctransport_test.go

fix(signal): handling errors

---

Dockerfile

fix(docker): build static executable file which not depend on dynamic librarys.

fix(docker): build static executable file which not depend on dynamic librarys.

---

cmd/signal/grpc/main.go
cmd/signal/grpc/server/server.go
examples/save-to-webm/server/main.go
go.sum

Done some refactoring allowing to set interceptors to grpc server and signal handlers.

grpc refactoring

---

.gitignore
go.sum
pkg/elements/decoder.go

we should not be concurrently reading and writing from/to the libvpx decoder
@sean-bauer

fix(decoder): implement rwlock for thread safety
